/* M:1:M의 관계를 UNION ALL로 해결
 * 성능을 고려, M_CUS를 인라인-뷰 바깥에서 한 번만 사용
 */

SELECT T1.CUS_ID
	  , MAX(T1.CUS_NM) 			AS CUS_NM
	  , SUM(T4.EVL_CNT)		    AS EVL_CNT
	  , SUM(T4.ORD_CNT)			AS ORD_CNT
FROM	M_CUS T1
	  , (
		SELECT T2.CUS_ID
		      , COUNT(*)	    AS EVL_CNT
		      , NULL			AS ORD_CNT
		FROM   T_ITM_EVL T2
		WHERE  1 = 1
		AND    T2.CUS_ID = 'CUS_0023'
		AND    T2.EVL_DT >= TO_DATE('20170301', 'YYYYMMDD')
		AND    T2.EVL_DT < TO_DATE('20170401', 'YYYYMMDD')
		GROUP BY T2.CUS_ID
		
		UNION ALL
		
		SELECT T3.CUS_ID
		      , NULL	        AS EVL_CNT
		      , COUNT(*)		AS ORD_CNT
		FROM   T_ORD T3
		WHERE  1 = 1
		AND    T3.CUS_ID = 'CUS_0023'
		AND    T3.ORD_DT >= TO_DATE('20170301', 'YYYYMMDD')
		AND    T3.ORD_DT < TO_DATE('20170401', 'YYYYMMDD')
		GROUP BY T3.CUS_ID
		) T4
WHERE   T1.CUS_ID = T4.CUS_ID
GROUP BY T1.CUS_ID;