/* M:1:M의 관계를 UNION ALL로 해결 */
		
SELECT T1.CUS_ID
	  , MAX(T1.CUS_NM) 			AS CUS_NM
	  , SUM(T1.EVL_CNT)		    AS EVL_CNT
	  , SUM(T1.ORD_CNT)			AS ORD_CNT
FROM	(
		SELECT T1.CUS_ID
		      , MAX(T1.CUS_NM) AS CUS_NM
		      , COUNT(*)	    AS EVL_CNT
		      , NULL			AS ORD_CNT
		FROM   M_CUS T1
			  , T_ITM_EVL T2
		WHERE  T1.CUS_ID = T2.CUS_ID
		AND    T2.CUS_ID = 'CUS_0023'
		AND    T2.EVL_DT >= TO_DATE('20170301', 'YYYYMMDD')
		AND    T2.EVL_DT < TO_DATE('20170401', 'YYYYMMDD')
		GROUP BY T1.CUS_ID, T1.CUS_NM 
		
		UNION ALL
		
		SELECT T1.CUS_ID
		      , MAX(T1.CUS_NM) AS CUS_NM
		      , NULL	        AS EVL_CNT
		      , COUNT(*)		AS ORD_CNT
		FROM   M_CUS T1
			  , T_ORD T3
		WHERE  T1.CUS_ID = T3.CUS_ID
		AND    T3.CUS_ID = 'CUS_0023'
		AND    T3.ORD_DT >= TO_DATE('20170301', 'YYYYMMDD')
		AND    T3.ORD_DT < TO_DATE('20170401', 'YYYYMMDD')
		GROUP BY T1.CUS_ID, T1.CUS_NM
		) T1
GROUP BY T1.CUS_ID;